version: '3'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  mysql:
    driver: ${VOLUMES_DRIVER}

services:
  ### NGINX Server #########################################
  nginx:
    build:
      context: .
      dockerfile: ./containers/nginx/Dockerfile
      args:
        - UID=${HOST_UID}
        - GID=${HOST_GID}
        - USERNAME=${HOST_NAME}
        - GROUPNAME=${HOST_GROUP}
    volumes:
      - ./application/backend/:/var/www/application
      - ./containers/nginx/logs/:/var/log/nginx
      - ./containers/nginx/ssl/:/etc/nginx/ssl
    ports:
      - "${NGINX_HOST_HTTP_PORT}:8080"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    networks:
      - backend
    depends_on:
      - golang
      - nuxt
  ### MySQL ################################################
  mysql:
    container_name: mysql
    build:
      context: ./containers/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=UTC
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - backend

  ### Nodejs(Nuxt) ################################################
  nuxt:
    container_name: nuxt
    build:
      context: .
      dockerfile: ./containers/nuxt/Dockerfile
      args:
        - UID=${HOST_UID}
        - GID=${HOST_GID}
        - USERNAME=${HOST_NAME}
        - GROUPNAME=${HOST_GROUP}
        - APP_NAME=${APP_NAME}
        - APP_ENV=${APP_ENV}
        - APP_DEBUG=${APP_DEBUG}
        - APP_URL=${APP_URL}
    environment:
      - EXEC_SETUP_FLAG=${EXEC_SETUP_FLAG} #yarn run build
    tty: true
    ports:
      - "${NUXT_PORT}:3000"
    volumes:
      - ./application/nuxt:/var/www/application:delegated
    networks:
      - backend
  ### Golang ################################################
  golang:
    tty: true
    build:
      context: .
      dockerfile: ./containers/go/Dockerfile
    volumes:
      - ./application/backend:/go/src/github.com/un_eating_meals/application/backend
    depends_on:
      - "mysql"
    environment:
      TZ: Asia/Tokyo
      DB_USER: 'root'
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_HOST: 'mysql'
    networks:
      - backend
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - nginx
    environment:
      DOMAINS: 'uneatingmeals.com -> http://nginx:8080'
      STAGE: production
    volumes:
      - ./org-chimata-ssl-certs:/var/lib/https-portal
    networks:
      - backend

