#sql-migrate設定ファイル
development:
  dialect: mysql
  datasource: ${DB_USER}:${DB_PASSWORD}@tcp(${DB_HOST}:3306)/un_eating_meals_db?parseTime=true #docker
  dir: database/migrations
  table: migrations
production:
  dialect: mysql
  datasource: ${DB_USER}:${DB_PASSWORD}@tcp(${DB_HOST}:3306)/un_eating_meals_db?parseTime=true
  dir: database/migrations
  table: migrations
